const PeopleData = [
  { name: "John Smith", email: "john.smith@gmail.com" },
  { name: "Jane Doe", email: "jane.doe@gmail.com" },
  { name: "Michael Brown", email: "michael.brown@gmail.com" },
  { name: "Emily Davis", email: "emily.davis@gmail.com" },
  { name: "Chris Wilson", email: "chris.wilson@gmail.com" },
  { name: "Sarah Johnson", email: "sarah.johnson@gmail.com" },
  { name: "Daniel Martinez", email: "daniel.martinez@gmail.com" },
  { name: "Laura Thompson", email: "laura.thompson@gmail.com" },
  { name: "James Anderson", email: "james.anderson@gmail.com" },
  { name: "Megan Lee", email: "megan.lee@gmail.com" },
  { name: "Andrew Clark", email: "andrew.clark@gmail.com" },
  { name: "Olivia Hall", email: "olivia.hall@gmail.com" },
  { name: "Joshua Young", email: "joshua.young@gmail.com" },
  { name: "Sophia Scott", email: "sophia.scott@gmail.com" },
  { name: "Brandon King", email: "brandon.king@gmail.com" },
  { name: "Jessica Wright", email: "jessica.wright@gmail.com" },
  { name: "David Hernandez", email: "david.hernandez@gmail.com" },
  { name: "Ashley Lopez", email: "ashley.lopez@gmail.com" },
  { name: "Kevin Hill", email: "kevin.hill@gmail.com" },
  { name: "Rachel Green", email: "rachel.green@gmail.com" },
  { name: "Ryan Adams", email: "ryan.adams@gmail.com" },
  { name: "Emma Carter", email: "emma.carter@gmail.com" },
  { name: "Zachary Roberts", email: "zachary.roberts@gmail.com" },
  { name: "Alyssa Evans", email: "alyssa.evans@gmail.com" },
  { name: "Nathan Collins", email: "nathan.collins@gmail.com" },
  { name: "Katherine Stewart", email: "katherine.stewart@gmail.com" },
  { name: "Justin Baker", email: "justin.baker@gmail.com" },
  { name: "Hannah Rivera", email: "hannah.rivera@gmail.com" },
  { name: "Tyler Murphy", email: "tyler.murphy@gmail.com" },
  { name: "Victoria Brooks", email: "victoria.brooks@gmail.com" },
];

export default PeopleData;
